---
minimum_pre_commit_version: 3.3.3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
        files: \.py$
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
        files: \.json$
      - id: check-yaml
        files: \.yaml$
      - id: debug-statements
      - id: pretty-format-json
        args:
          - --autofix
        files: \.json$
      - id: trailing-whitespace
        files: \.py$
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --recursive
          - --ignore-pass-statements
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: ["-c", "pre_commit.toml"]
        additional_dependencies: ["bandit[toml]"]