#---------------------------------------------------------------------------
# Workflow to run 101 MNIST Notebook
# Authors - Noopur, Payal Chaurasiya
#---------------------------------------------------------------------------
name: Workflow Interface 101 MNIST Notebook

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  wf_local_101_mnist:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
    - name: Checkout OpenFL repository
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 2 # needed for detecting changes
        submodules: "true"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Papermill Package
      run: python -m pip install --upgrade pip ipython ipykernel papermill

    - name: Run Notebook
      run: |
        cd openfl-tutorials/experimental/workflow
        papermill 101_MNIST.ipynb 101_MNIST_output.ipynb --request-save-on-cell-execute --log-output --autosave-cell-every 30
        echo "Notebook run completed"

    - name: Tar files
      run: tar -cvf notebook.tar ./openfl-tutorials/experimental/workflow/101_MNIST_output.ipynb

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      if: ${{ always() }}   # collect artifacts regardless of failures
      with:
        name: wf_interface_101_mnist_${{ github.run_id }}
        path: notebook.tar
